# 前端 Dockerfile - 使用 node:14 兼容 node-sass@4.12.0
FROM node:14 AS builder

WORKDIR /app
COPY recruit-system/recruit-web/package.json ./
COPY recruit-system/recruit-web/yarn.lock ./
RUN yarn install --registry=https://registry.npmmirror.com

COPY recruit-system/recruit-web/ .
RUN yarn build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
